import { describe, expect, it, vi } from 'vitest';
import { bootstrapInteractiveWeb } from './browser-bootstrap.js';

describe('Interactive web browser bootstrap', () => {
  it('mounts the current canonical site graph without inventing routes', () => {
    const canvas = { getBoundingClientRect: () => ({ left: 0, top: 0, width: 320, height: 180 }), addEventListener: vi.fn(), removeEventListener: vi.fn() };
    const navigate = vi.fn(); const onFocus = vi.fn(); const dispose = vi.fn(); const focusNode = vi.fn(); const mountSurface = vi.fn(() => ({ dispose, focusNode }));
    const runtime = bootstrapInteractiveWeb({ canvas, navigate, onFocus, mountSurface });
    expect(runtime.experience.frame.productKind).toBe('interactive-web-site'); expect(runtime.experience.frame.presentationMediaId).toBe('r01-dojo-environment'); expect(runtime.experience.frame.nodes[0]).toEqual(expect.objectContaining({ id: 'home', label: 'TAIJIFU', canonicalUrl: '/' })); expect(runtime.experience.frame.nodes).toContainEqual(expect.objectContaining({ id: 'tai', label: 'TAI', canonicalUrl: '/pt-br/principios/tai/', parentId: 'fundamentos' })); expect(mountSurface).toHaveBeenNthCalledWith(1, { canvas, frame: runtime.experience.frame, navigate, onFocus: expect.any(Function) }); runtime.focusNode('tai'); expect(focusNode).toHaveBeenCalledWith('tai'); const focused = bootstrapInteractiveWeb({ canvas, navigate, mountSurface, initialFocusNode: 'fu' }); expect(focusNode).toHaveBeenLastCalledWith('fu'); focused.dispose(); runtime.dispose(); expect(dispose).toHaveBeenCalledTimes(2);
  });
  it('selects presentation media from the explicit route contract', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,routeId:'fundamentos'}); expect(runtime.experience.frame.presentationMediaId).toBe('p02-dojo-interior'); });
  it('does not invent presentation media for an unmapped route', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,routeId:'historia'}); expect(runtime.experience.frame.presentationMediaId).toBeUndefined(); });
  it('allows an explicit governed presentation-media slot to override route selection', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,routeId:'fundamentos',presentationMediaId:'p03-martial-landscape'}); expect(runtime.experience.frame.presentationMediaId).toBe('p03-martial-landscape'); });
  it('reports governed media changes when the live surface focus changes', () => { let surfaceOnFocus:any; const mountSurface=vi.fn((options)=>{surfaceOnFocus=options.onFocus;return{dispose:vi.fn(),focusNode:vi.fn()};}); const onFocus=vi.fn(); const onPresentationMediaChange=vi.fn(); bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,onFocus,onPresentationMediaChange}); surfaceOnFocus?.({nodeId:'fundamentos',label:'Fundamentos',canonicalUrl:'/pt-br/fundamentos/'}); expect(onFocus).toHaveBeenCalledWith(expect.objectContaining({nodeId:'fundamentos'})); expect(onPresentationMediaChange).toHaveBeenLastCalledWith('p02-dojo-interior'); surfaceOnFocus?.({nodeId:'historia',label:'História',canonicalUrl:'/pt-br/historia/'}); expect(onPresentationMediaChange).toHaveBeenLastCalledWith(undefined); });
  it('drives a DOM presentation overlay from governed route media', () => { let surfaceOnFocus:any; const mountSurface=vi.fn((options)=>{surfaceOnFocus=options.onFocus;return{dispose:vi.fn(),focusNode:vi.fn()};}); const presentationMediaElement=document.createElement('img'); bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,presentationMediaElement}); expect(presentationMediaElement.dataset.presentationMediaId).toBe('r01-dojo-environment'); expect(presentationMediaElement.getAttribute('src')).toBe('/media/p08-brand-book-background.svg'); surfaceOnFocus?.({nodeId:'fundamentos',label:'Fundamentos',canonicalUrl:'/pt-br/fundamentos/'}); expect(presentationMediaElement.dataset.presentationMediaId).toBe('p02-dojo-interior'); surfaceOnFocus?.({nodeId:'historia',label:'História',canonicalUrl:'/pt-br/historia/'}); expect(presentationMediaElement.hidden).toBe(true); });
  it('stops overlay mutations when the runtime is disposed', () => { let surfaceOnFocus:any; const mountSurface=vi.fn((options)=>{surfaceOnFocus=options.onFocus;return{dispose:vi.fn(),focusNode:vi.fn()};}); const presentationMediaElement=document.createElement('img'); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,presentationMediaElement}); runtime.dispose(); surfaceOnFocus?.({nodeId:'historia',label:'História',canonicalUrl:'/pt-br/historia/'}); expect(presentationMediaElement.dataset.presentationMediaId).toBe('r01-dojo-environment'); expect(presentationMediaElement.hidden).toBe(false); });
  it('exposes presentation media state through the runtime API', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const presentationMediaElement=document.createElement('img'); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,presentationMediaElement}); expect(runtime.getPresentationMediaSnapshot()).toEqual({status:'visible',mediaId:'r01-dojo-environment'}); runtime.dispose(); expect(runtime.getPresentationMediaSnapshot()).toEqual({status:'disposed',mediaId:'r01-dojo-environment'}); });
  it('returns a neutral media snapshot when no presentation element is mounted', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface}); expect(runtime.getPresentationMediaSnapshot()).toEqual({status:'idle',mediaId:undefined}); runtime.dispose(); expect(runtime.getPresentationMediaSnapshot()).toEqual({status:'disposed',mediaId:undefined}); });
  it('uses the governed locale when building the interactive experience', () => { const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,locale:'pt-BR'}); expect(runtime.experience.frame.nodes).toContainEqual(expect.objectContaining({id:'historia',label:'História'})); });
  it('mounts personalized training only when a training root is supplied', () => { const canvas={} as never; const trainingRoot=document.createElement('section'); const trainingDispose=vi.fn(); const mountTraining=vi.fn(()=>({getState:vi.fn(),dispose:trainingDispose})); const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas,navigate:vi.fn(),mountSurface,trainingRoot,mountTraining}); expect(mountTraining).toHaveBeenCalledOnce(); expect(runtime.trainingAvailable).toBe(true); runtime.dispose(); expect(trainingDispose).toHaveBeenCalledOnce(); });
  it('does not mount personalized training on routes without its root', () => { const mountTraining=vi.fn(); const mountSurface=vi.fn(()=>({dispose:vi.fn(),focusNode:vi.fn()})); const runtime=bootstrapInteractiveWeb({canvas:{} as never,navigate:vi.fn(),mountSurface,mountTraining}); expect(mountTraining).not.toHaveBeenCalled(); expect(runtime.trainingAvailable).toBe(false); });
});
