import { buildLocalizedExperienceNodes, canonToExperienceNodes, getExperienceContext } from './content/canon-registry.js';
import { parseLocalePrefix, type SupportedLocale } from './content/locale.js';
import { canonSnapshot } from './content/canon-snapshot.js';
import { canonCurriculumOverview, canonGraduationGroups, canonMethodGroups, type CanonCurriculumGroup } from './content/canon-curriculum-pages.js';
import { getOfficialPageContent, type ContentBlock } from './content/official-page-content.js';
import { findLocalizedRoute, findSiteRoute, primaryNavigation, resolveLegacyRedirect, siteRoutes } from './content/site-ia.js';
import { getEditorialScope } from './content/editorial-scope.js';
import { editorialSurfaceClass } from './editorial-surface.js';

function escapeHtml(value: string): string { return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll("'", '&#39;'); }
export function renderPrimaryNavigation(locale: SupportedLocale = 'pt-BR'): string { return primaryNavigation.map((id) => findLocalizedRoute(id, locale)).filter((route) => route !== null).map((route) => `<a href="${escapeHtml(route.canonicalUrl)}">${escapeHtml(route.title)}</a>`).join(''); }
function renderBlock(block: ContentBlock): string { switch (block.kind) { case 'paragraph': return `<p>${escapeHtml(block.text)}</p>`; case 'quote': return `<blockquote>${escapeHtml(block.text)}</blockquote>`; case 'notice': return `<p class="canon-reconciliation">${escapeHtml(block.text)}</p>`; case 'list': return `<section class="content-list">${block.title ? `<h2>${escapeHtml(block.title)}</h2>` : ''}<ul>${block.items.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></section>`; case 'stats': return `<div class="canon-stats">${block.items.map((item) => `<article><strong>${escapeHtml(item.value)}</strong><span>${escapeHtml(item.label)}</span></article>`).join('')}</div>`; case 'axes': return `<div class="principle-grid">${block.items.map((item) => `<article class="principle-card principle-card--${escapeHtml(item.id)}"><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.meaning)}</p><blockquote>${escapeHtml(item.question)}</blockquote></article>`).join('')}</div>`; } }
function renderCurriculumGroups(groups: readonly CanonCurriculumGroup[]): string { return `<section class="canon-curriculum" aria-label="Currículo TAIJIFU"><header class="canon-curriculum__header"><p>174 entidades nesta release: 4 Bases, 10 Faixas, 32 Caminhos e 128 Núcleos.</p></header>${groups.map((group) => `<details class="canon-curriculum__group" data-belt-id="${escapeHtml(group.id)}"><summary>${escapeHtml(group.title)} · ${group.items.length} ${group.items.length === 1 ? 'Caminho' : 'Caminhos'}</summary>${group.summary ? `<p>${escapeHtml(group.summary)}</p>` : ''}<div class="canon-curriculum__items">${group.items.map((item) => item.details.length > 0 ? `<details class="canon-curriculum__item" data-path-id="${escapeHtml(item.id)}"><summary>${escapeHtml(item.title)} · ${item.nucleusCount} ${item.nucleusCount === 1 ? 'Núcleo' : 'Núcleos'}</summary><p>${escapeHtml(item.summary)}</p><ul>${item.details.map((detail, index) => `<li data-nucleus-index="${index + 1}">${escapeHtml(detail)}</li>`).join('')}</ul></details>` : `<article class="canon-curriculum__item" data-path-id="${escapeHtml(item.id)}"><h3>${escapeHtml(item.title)} · ${item.nucleusCount} ${item.nucleusCount === 1 ? 'Núcleo' : 'Núcleos'}</h3><p>${escapeHtml(item.summary)}</p></article>`).join('')}</div></details>`).join('')}</section>`; }
function renderCanonBases(): string { return `<section class="canon-bases" aria-labelledby="canon-bases-title"><header class="canon-bases__header"><p class="content-entry__type">TAIJIFU-CANON-1.0</p><h2 id="canon-bases-title">Bases canônicas</h2><p>As 4 Bases da release. Esta camada é apresentada separadamente porque a release não define uma relação Base → Faixa nos dados canônicos.</p></header><div class="canon-bases__grid">${canonSnapshot.bases.map((base) => `<article class="canon-base" data-base-id="${escapeHtml(base.id)}"><p class="canon-base__id">${escapeHtml(base.id)}</p><h3>${escapeHtml(base.name)}</h3><p>${escapeHtml(base.function)}</p><dl><div><dt>Elemento</dt><dd>${escapeHtml(base.element)}</dd></div><div><dt>Animal</dt><dd>${escapeHtml(base.animal)}</dd></div><div><dt>Cor</dt><dd>${escapeHtml(base.color)}</dd></div></dl></article>`).join('')}</div></section>`; }
function renderCurriculumOverview(): string { return `<section class="curriculum-overview" aria-labelledby="curriculum-overview-title"><header class="curriculum-overview__header"><p class="content-entry__type">TAIJIFU-CANON-1.0</p><h2 id="curriculum-overview-title">Percurso canônico</h2><p>Visão estrutural das faixas, Caminhos e Núcleos desta release.</p></header><ol class="curriculum-overview__journey">${canonCurriculumOverview.map((belt) => `<li class="curriculum-overview__belt" data-belt-id="${escapeHtml(belt.id)}"><span class="curriculum-overview__order">${String(belt.order).padStart(2, '0')}</span><div><strong>${escapeHtml(belt.title)}</strong><span>${escapeHtml(belt.function)}</span></div><small>${belt.pathCount} ${belt.pathCount === 1 ? 'Caminho' : 'Caminhos'} · ${belt.nucleusCount} Núcleos</small></li>`).join('')}</ol><nav class="curriculum-overview__actions" aria-label="Explorar currículo"><a href="/graduacao/">Ver Graduação</a><a href="/metodo/">Explorar Método e Núcleos</a></nav></section>`; }
const principleIds = Object.freeze(['tai', 'ji', 'fu']);
function renderContextNavigation(route: NonNullable<ReturnType<typeof findSiteRoute>>, locale: SupportedLocale): string { const context = getExperienceContext(route.id); const project = (id: string) => findLocalizedRoute(id, locale); const items: string[] = []; const parent = context.parent ? project(context.parent.id) : null; const previous = context.previous ? project(context.previous.id) : null; const next = context.next ? project(context.next.id) : null; if (parent?.canonicalUrl) items.push(`<a href="${escapeHtml(parent.canonicalUrl)}" data-context-relation="parent">↑ ${escapeHtml(parent.title)}</a>`); if (previous?.canonicalUrl && previous.id !== 'home') items.push(`<a href="${escapeHtml(previous.canonicalUrl)}" data-context-relation="previous" rel="prev">← ${escapeHtml(previous.title)}</a>`); if (next?.canonicalUrl) items.push(`<a href="${escapeHtml(next.canonicalUrl)}" data-context-relation="next" rel="next">${escapeHtml(next.title)} →</a>`); return items.length > 0 ? `<nav class="content-context" aria-label="Jornada TAIJIFU">${items.join('')}</nav>` : ''; }
function renderPrincipleLinks(locale: SupportedLocale): string { return `<nav class="principle-links" aria-label="Princípios TAIJIFU">${principleIds.map((id) => { const route = findLocalizedRoute(id, locale); return route ? `<a class="principle-links__item principle-links__item--${escapeHtml(id)}" href="${escapeHtml(route.canonicalUrl)}"><strong>${escapeHtml(route.title)}</strong><span>Explorar princípio</span></a>` : ''; }).join('')}</nav>`; }
export function renderSemanticRoute(pathname: string): string | null { const route = findSiteRoute(pathname); const locale = parseLocalePrefix(pathname) ?? 'pt-BR'; const localizedRoute = route ? findLocalizedRoute(route.id, locale) : null; if (!route || !localizedRoute || route.id === 'home') return null; const content = getOfficialPageContent(route.id); const editorialScope = getEditorialScope(route.id); const curriculumGroups = route.id === 'metodo' ? canonMethodGroups : route.id === 'graduacao' ? canonGraduationGroups : null; const blocks = content?.blocks.filter((block) => !((curriculumGroups || route.id === 'influencias') && block.kind === 'notice' && block.text.includes('ainda não recuperado'))) ?? []; const canonBases = route.id === 'metodo' || route.id === 'influencias' ? renderCanonBases() : ''; const body = content && editorialScope?.state === 'official' ? `<p class="content-lead">${escapeHtml(content.lead)}</p>${blocks.map(renderBlock).join('')}${route.id === 'graduacao' ? renderCurriculumOverview() : ''}${canonBases}${curriculumGroups ? renderCurriculumGroups(curriculumGroups) : ''}<p class="content-source">Fonte de autoridade: ${escapeHtml(curriculumGroups || route.id === 'influencias' ? 'TAIJIFU-CANON-1.0 snapshot' : content.sourceAuthority)}</p>` : `<p class="canon-reconciliation">O corpo oficial desta seção está em reconciliação. A rota canônica permanece publicada, mas nenhum conteúdo não verificado será inventado.</p>`; const principleId = principleIds.includes(route.id) ? route.id : null; const isManifesto = route.id === 'manifesto'; const editorialClass = editorialSurfaceClass(route.id) ?? 'editorial-surface'; const routeClass = `content-page--${escapeHtml(route.id)}`; const pageClass = principleId ? `content-page content-page--principle content-page--${principleId} ${routeClass} ${editorialClass}` : isManifesto ? `content-page content-page--manifesto ${routeClass} ${editorialClass}` : `content-page ${routeClass} ${editorialClass}`; const surfaceAttribute = principleId ? ` data-principle="${principleId}"` : isManifesto ? ' data-surface="manifesto"' : ''; return `<section class="${pageClass}"${surfaceAttribute} aria-labelledby="page-title"><header class="content-page__header"><p class="content-entry__type">${escapeHtml(content?.eyebrow ?? 'TAIJIFU')}</p><h1 id="page-title">${escapeHtml(localizedRoute.title)}</h1></header><div class="content-page__body">${body}${route.id === 'fundamentos' ? renderPrincipleLinks(locale) : ''}${renderContextNavigation(route, locale)}<nav class="content-navigation" aria-label="Navegação TAIJIFU">${renderPrimaryNavigation(locale)}</nav></div></section>`; }
export function renderInteractiveLegend(locale: SupportedLocale = 'pt-BR'): string { return buildLocalizedExperienceNodes(locale).map((node) => `<a data-node-id="${escapeHtml(node.id)}" href="${escapeHtml(node.canonicalUrl)}">${escapeHtml(node.label)}</a>`).join(''); }
export function canonicalRedirectFor(pathname: string): string | null { return resolveLegacyRedirect(pathname); }
