import * as THREE from 'three';
import type { ExperienceNode } from './experience-shell.js';
import type { RenderFrame } from './renderer-adapter.js';
import { dojoHotspotRole } from './dojo-hotspots.js';
import { sceneVisualToken } from './tkn-scene-grammar.js';
import { semanticColorToken } from './tkn-semantic-palette.js';
import { spatialLayoutToken } from './tkn-spatial-grammar.js';
import { surfaceVisualToken, type TknSurface } from './tkn-surface-grammar.js';

export type ThreeSceneProjection = Readonly<{ scene: THREE.Scene; camera: THREE.PerspectiveCamera; nodes: readonly THREE.Object3D[] }>;
function surfaceMaterial(surface:TknSurface,color:number,extra:THREE.MeshStandardMaterialParameters={}):THREE.MeshStandardMaterial{const token=surfaceVisualToken(surface);return new THREE.MeshStandardMaterial({color,roughness:token.roughness,metalness:token.metalness,opacity:token.opacity,transparent:token.transparent,...extra});}
function gridPosition(index:number,count:number):THREE.Vector3{const layout=spatialLayoutToken('layout');const columns=Math.ceil(Math.sqrt(count));const rows=Math.ceil(count/columns);return new THREE.Vector3((index%columns-(columns-1)/2)*layout.gridColumnGap,((rows-1)/2-Math.floor(index/columns))*layout.gridRowGap,0);}
function radialPosition(index:number,count:number,radius:number):THREE.Vector3{const angle=(index/Math.max(count,1))*Math.PI*2-Math.PI/2;return new THREE.Vector3(Math.cos(angle)*radius,Math.sin(angle)*radius,0);}
function hierarchyDepth(node:ExperienceNode,byId:ReadonlyMap<string,ExperienceNode>):number{let depth=0;let current:ExperienceNode|undefined=node;const visited=new Set<string>();while(current?.parentId&&!visited.has(current.id)){visited.add(current.id);const parent=byId.get(current.parentId);if(!parent)break;depth+=1;current=parent;}return depth;}
function hierarchicalPosition(node:ExperienceNode,nodes:readonly ExperienceNode[],byId:ReadonlyMap<string,ExperienceNode>):THREE.Vector3{const canonical=node.id==='home'||node.id==='tai'||node.id==='ji'||node.id==='fu'?spatialLayoutToken(node.id):null;if(canonical)return new THREE.Vector3(canonical.x,canonical.y,canonical.z);const layout=spatialLayoutToken('layout');const depth=Math.max(1,hierarchyDepth(node,byId));const peers=nodes.filter((candidate)=>Math.max(1,hierarchyDepth(candidate,byId))===depth);const peerIndex=peers.findIndex((candidate)=>candidate.id===node.id);return radialPosition(peerIndex,peers.length,layout.canonicalRadius+(depth-1)*layout.depthRadiusStep).setY(1.35-Math.min(depth-1,2)*layout.depthYStep);}
function addDojoArchitecture(scene:THREE.Scene):void{const visual=sceneVisualToken('dojo');const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,18),surfaceMaterial('ground',visual.ground));floor.rotation.x=-Math.PI/2;floor.position.y=0;floor.userData.decorative=true;scene.add(floor);const wallMaterial=surfaceMaterial('architecture',visual.architecture);const backWall=new THREE.Mesh(new THREE.PlaneGeometry(18,7),wallMaterial);backWall.position.set(0,3.5,-3.2);scene.add(backWall);const sideWall=new THREE.Mesh(new THREE.PlaneGeometry(18,7),wallMaterial);sideWall.rotation.y=Math.PI/2;sideWall.position.set(-8,3.5,2);scene.add(sideWall);const threshold=new THREE.Mesh(new THREE.BoxGeometry(8.5,0.08,0.7),surfaceMaterial('architecture',visual.threshold,{emissive:visual.thresholdEmissive,emissiveIntensity:1.2}));threshold.position.set(0,0.05,-2.65);scene.add(threshold);const centralLight=new THREE.PointLight(visual.centralLight,visual.centralLightIntensity,visual.centralLightDistance,visual.centralLightDecay);centralLight.position.set(0,4.4,-1.5);scene.add(centralLight);}
function addCanonicalConnections(scene:THREE.Scene,nodes:readonly THREE.Object3D[]):void{const visual=sceneVisualToken('dojo');const byId=new Map(nodes.map((node)=>[node.userData.nodeId as string,node]));const material=new THREE.LineBasicMaterial({color:visual.connection,transparent:true,opacity:0.38});let connectionCount=0;for(const node of nodes){const parentId=node.userData.parentId as string|undefined;if(!parentId)continue;const parent=byId.get(parentId);if(!parent)continue;const geometry=new THREE.BufferGeometry().setFromPoints([parent.position,node.position]);const connection=new THREE.Line(geometry,material);connection.userData={parentId,childId:node.userData.nodeId,decorative:true};scene.add(connection);connectionCount+=1;}scene.userData.connectionCount=connectionCount;}
export function createThreeScene(frame:RenderFrame):ThreeSceneProjection{const visual=sceneVisualToken('dojo');const scene=new THREE.Scene();const hasCanonicalRoot=frame.nodes.some((node)=>node.id==='home');scene.userData.productKind=frame.productKind;scene.userData.layoutKind=hasCanonicalRoot?'dojo-canonical-hierarchy':'fallback-grid';scene.background=new THREE.Color(visual.background);const camera=new THREE.PerspectiveCamera(68,1,0.1,100);camera.position.set(0,1.65,5);camera.lookAt(0,1.5,-1);scene.add(new THREE.HemisphereLight(visual.hemisphereSky,visual.hemisphereGround,visual.hemisphereIntensity));addDojoArchitecture(scene);const byId=new Map(frame.nodes.map((node)=>[node.id,node]));const spatialById=new Map(frame.spatialNodes.map((node)=>[node.nodeId,node]));const manifestationById=new Map(frame.manifestationNodes.map((node)=>[node.nodeId,node]));const nodes=frame.nodes.map((node,index)=>{const isRoot=node.id==='home';const role=dojoHotspotRole(node.id);const geometry=isRoot?new THREE.CylinderGeometry(0.72,0.84,0.22,48):new THREE.BoxGeometry(1.35,1.35,0.18,4,4,1);const semantic=semanticColorToken(node.id);const material=surfaceMaterial('dojo',semantic.color,{emissive:semantic.color,emissiveIntensity:isRoot?0.16:0.05});const mesh=new THREE.Mesh(geometry,material);mesh.position.copy(hasCanonicalRoot?hierarchicalPosition(node,frame.nodes,byId):gridPosition(index,frame.nodes.length));mesh.rotation.x=isRoot?0:-0.08;const spatial=spatialById.get(node.id);const manifestation=manifestationById.get(node.id);mesh.userData={nodeId:node.id,label:node.label,canonicalUrl:node.canonicalUrl,parentId:node.parentId,visualRole:isRoot?'origin':role,baseZ:mesh.position.z,structure:spatial?.structure??'default',semanticRank:semantic.rank,manifestationIntensity:manifestation?.intensity??'signal'};scene.add(mesh);return mesh;});addCanonicalConnections(scene,nodes);return Object.freeze({scene,camera,nodes:Object.freeze(nodes)});}
