import { describe, expect, it } from 'vitest';
import { BoxGeometry, Mesh, MeshStandardMaterial, Object3D, PerspectiveCamera } from 'three';
import { applyProjectedFocus, describeProjectedFocus } from './three-focus.js';

function materialNode(id:string,x:number):Mesh { const material=new MeshStandardMaterial({color:0xe9e0cf,emissive:0xe9e0cf,emissiveIntensity:0.05,opacity:1,transparent:true}); const node=new Mesh(new BoxGeometry(1,1,1),material); node.position.set(x,0,0); node.userData={nodeId:id,label:id.toUpperCase(),canonicalUrl:`/${id}/`,baseZ:0,baseEmissiveIntensity:0.05,baseOpacity:1}; return node; }

describe('Three projected focus',()=>{
  it('describes only canonical projected nodes',()=>{const node=new Object3D();node.userData={nodeId:'tai',label:'TAI',canonicalUrl:'/principios/tai/'};expect(describeProjectedFocus(node)).toEqual({nodeId:'tai',label:'TAI',canonicalUrl:'/principios/tai/'});expect(describeProjectedFocus(new Object3D())).toBeNull();});
  it('keeps TAI JI FU as structural peers even when one is the current route',()=>{const camera=new PerspectiveCamera();camera.position.set(0,0,8.5);const tai=materialNode('tai',3);const ji=materialNode('ji',0);const fu=materialNode('fu',-3);applyProjectedFocus([tai,ji,fu],null,camera,false,tai);for(const node of [tai,ji,fu]){expect(node.scale.x).toBe(1);expect(node.position.z).toBe(0);expect((node.material as MeshStandardMaterial).emissiveIntensity).toBeCloseTo(0.05);expect((node.material as MeshStandardMaterial).opacity).toBe(1);}expect(tai.userData.focusState).toBe('current');expect(ji.userData.focusState).toBe('peer');expect(fu.userData.focusState).toBe('peer');});
  it('allows temporary focus without demoting the other TAI JI FU peers',()=>{const camera=new PerspectiveCamera();camera.position.set(0,0,8.5);const tai=materialNode('tai',3);const ji=materialNode('ji',0);const fu=materialNode('fu',-3);applyProjectedFocus([tai,ji,fu],fu,camera,false,tai);expect(fu.userData.focusState).toBe('focused');expect(fu.scale.x).toBeCloseTo(1.18);for(const node of [tai,ji]){expect(node.scale.x).toBe(1);expect((node.material as MeshStandardMaterial).opacity).toBe(1);}expect(tai.userData.focusState).toBe('current');expect(ji.userData.focusState).toBe('peer');});
  it('restores geometry and material without changing canonical metadata',()=>{const camera=new PerspectiveCamera();camera.position.set(0,0,8.5);const tai=materialNode('tai',3);tai.userData.canonicalUrl='/principios/tai/';const manifesto=materialNode('manifesto',-3);applyProjectedFocus([tai,manifesto],tai,camera);expect(tai.userData.focusState).toBe('focused');expect(manifesto.userData.focusState).toBe('receded');expect(tai.userData.canonicalUrl).toBe('/principios/tai/');applyProjectedFocus([tai,manifesto],null,camera);expect(tai.scale.x).toBe(1);expect(tai.position.z).toBe(0);expect(tai.userData.focusState).toBe('neutral');expect((tai.material as MeshStandardMaterial).emissiveIntensity).toBeCloseTo(0.05);expect((tai.material as MeshStandardMaterial).opacity).toBe(1);});
  it('keeps the camera anchored when reduced motion is requested while retaining material hierarchy',()=>{const camera=new PerspectiveCamera();camera.position.set(0,0,8.5);const node=materialNode('tai',3);node.position.y=2;applyProjectedFocus([node],node,camera,true);expect(camera.position.x).toBe(0);expect(camera.position.y).toBe(0);expect(node.userData.focusState).toBe('focused');expect((node.material as MeshStandardMaterial).emissiveIntensity).toBeCloseTo(0.28);});
});
