import { Mesh, MeshStandardMaterial, type Camera, type Object3D } from 'three';
import type { CanonicalNavigation } from './three-navigation.js';

export type ProjectedFocus=CanonicalNavigation&Readonly<{label:string}>;
type FocusState='focused'|'current'|'peer'|'receded'|'neutral';
const TAIJIFU_PEERS=new Set(['tai','ji','fu']);
function baseZ(node:Object3D):number{const value=node.userData.baseZ;return typeof value==='number'?value:0;}
function isTaijifuPeer(node:Object3D|null):boolean{return !!node&&TAIJIFU_PEERS.has(node.userData.nodeId as string);}
function applyMaterialFocus(node:Object3D,state:FocusState):void{if(!(node instanceof Mesh)||!(node.material instanceof MeshStandardMaterial))return;const material=node.material;const baseEmissive=typeof node.userData.baseEmissiveIntensity==='number'?node.userData.baseEmissiveIntensity:material.emissiveIntensity;const baseOpacity=typeof node.userData.baseOpacity==='number'?node.userData.baseOpacity:material.opacity;if(typeof node.userData.baseEmissiveIntensity!=='number')node.userData.baseEmissiveIntensity=baseEmissive;if(typeof node.userData.baseOpacity!=='number')node.userData.baseOpacity=baseOpacity;material.transparent=true;material.emissiveIntensity=state==='focused'?Math.max(baseEmissive,0.28):state==='current'&&!isTaijifuPeer(node)?Math.max(baseEmissive,0.14):state==='receded'?Math.min(baseEmissive,0.02):baseEmissive;material.opacity=state==='current'&&!isTaijifuPeer(node)?Math.min(baseOpacity,0.82):state==='receded'?Math.min(baseOpacity,0.42):baseOpacity;material.needsUpdate=true;}
export function describeProjectedFocus(node:Object3D|null):ProjectedFocus|null{if(!node)return null;const{nodeId,label,canonicalUrl}=node.userData;if(typeof nodeId!=='string'||typeof label!=='string'||typeof canonicalUrl!=='string')return null;return Object.freeze({nodeId,label,canonicalUrl});}
export function applyProjectedFocus(nodes:readonly Object3D[],focused:Object3D|null,camera:Camera,reducedMotion=false,current:Object3D|null=null):void{const peerContext=isTaijifuPeer(current)||isTaijifuPeer(focused);for(const node of nodes){const isFocused=node===focused;const isCurrent=node===current;const isPeer=peerContext&&isTaijifuPeer(node);const hasContext=focused!==null||current!==null;const state:FocusState=isFocused&&!isCurrent?'focused':isCurrent?'current':isPeer?'peer':hasContext?'receded':'neutral';const structuralPeer=isPeer&&!isFocused;node.scale.setScalar(state==='focused'?1.18:structuralPeer?1:state==='current'?1.08:state==='receded'?0.88:1);node.position.z=baseZ(node)+(state==='focused'?0.36:structuralPeer?0:state==='current'?0.16:0);node.userData.focusState=state;applyMaterialFocus(node,state);}const cameraTarget=focused??current;if(reducedMotion||!cameraTarget){camera.position.x=0;camera.position.y=0;camera.lookAt(0,0,0);camera.updateMatrixWorld(true);return;}camera.position.x=cameraTarget.position.x*0.08;camera.position.y=cameraTarget.position.y*0.08;camera.lookAt(cameraTarget.position.x*0.18,cameraTarget.position.y*0.18,0);camera.updateMatrixWorld(true);}
