import * as THREE from 'three';
import type { ExperienceNode } from './experience-shell.js';
import type { RenderFrame } from './renderer-adapter.js';
import { dojoHotspotRole } from './dojo-hotspots.js';
import { sceneVisualToken } from './tkn-scene-grammar.js';
import { semanticColorToken } from './tkn-semantic-palette.js';
import { spatialLayoutToken } from './tkn-spatial-grammar.js';
import { geometryVisualToken } from './tkn-geometry-grammar.js';
import { cameraVisualToken } from './tkn-camera-grammar.js';
import { environmentGeometryToken } from './tkn-environment-geometry-grammar.js';
import { connectionVisualToken } from './tkn-connection-grammar.js';
import { surfaceVisualToken, type TknSurface } from './tkn-surface-grammar.js';

export type ThreeSceneProjection = Readonly<{ scene: THREE.Scene; camera: THREE.PerspectiveCamera; nodes: readonly THREE.Object3D[] }>;
function surfaceMaterial(surface:TknSurface,color:number,extra:THREE.MeshStandardMaterialParameters={}):THREE.MeshStandardMaterial{const token=surfaceVisualToken(surface);return new THREE.MeshStandardMaterial({color,roughness:token.roughness,metalness:token.metalness,opacity:token.opacity,transparent:token.transparent,...extra});}
function gridPosition(index:number,count:number):THREE.Vector3{const layout=spatialLayoutToken('layout');const columns=Math.ceil(Math.sqrt(count));const rows=Math.ceil(count/columns);return new THREE.Vector3((index%columns-(columns-1)/2)*layout.gridColumnGap,((rows-1)/2-Math.floor(index/columns))*layout.gridRowGap,0);}
function radialPosition(index:number,count:number,radius:number):THREE.Vector3{const angle=(index/Math.max(count,1))*Math.PI*2-Math.PI/2;return new THREE.Vector3(Math.cos(angle)*radius,Math.sin(angle)*radius,0);}
function hierarchyDepth(node:ExperienceNode,byId:ReadonlyMap<string,ExperienceNode>):number{let depth=0;let current:ExperienceNode|undefined=node;const visited=new Set<string>();while(current?.parentId&&!visited.has(current.id)){visited.add(current.id);const parent=byId.get(current.parentId);if(!parent)break;depth+=1;current=parent;}return depth;}
function hierarchicalPosition(node:ExperienceNode,nodes:readonly ExperienceNode[],byId:ReadonlyMap<string,ExperienceNode>):THREE.Vector3{const canonical=node.id==='home'||node.id==='tai'||node.id==='ji'||node.id==='fu'?spatialLayoutToken(node.id):null;if(canonical)return new THREE.Vector3(canonical.x,canonical.y,canonical.z);const layout=spatialLayoutToken('layout');const depth=Math.max(1,hierarchyDepth(node,byId));const peers=nodes.filter((candidate)=>Math.max(1,hierarchyDepth(candidate,byId))===depth);const peerIndex=peers.findIndex((candidate)=>candidate.id===node.id);return radialPosition(peerIndex,peers.length,layout.canonicalRadius+(depth-1)*layout.depthRadiusStep).setY(1.35-Math.min(depth-1,2)*layout.depthYStep);}
function geometryForRole(role:'origin'|'principle'):THREE.BufferGeometry{const token=geometryVisualToken(role);if(token.shape==='cylinder')return new THREE.CylinderGeometry(token.dimensions[0],token.dimensions[1],token.dimensions[2],token.segments);return new THREE.BoxGeometry(token.dimensions[0],token.dimensions[1],token.dimensions[2],token.segments,token.segments,1);}
function environmentGeometry(kind:'floor'|'back-wall'|'side-wall'|'threshold'):THREE.BufferGeometry{const token=environmentGeometryToken(kind);if(token.shape==='plane')return new THREE.PlaneGeometry(token.dimensions[0],token.dimensions[1]);return new THREE.BoxGeometry(token.dimensions[0],token.dimensions[1],token.dimensions[2]);}
function applyEnvironmentTransform(object:THREE.Object3D,kind:'floor'|'back-wall'|'side-wall'|'threshold'):void{const token=environmentGeometryToken(kind);object.position.set(...token.position);object.rotation.x=token.rotationX;object.rotation.y=token.rotationY;}
function addDojoArchitecture(scene:THREE.Scene):void{const visual=sceneVisualToken('dojo');const floor=new THREE.Mesh(environmentGeometry('floor'),surfaceMaterial('ground',visual.ground));applyEnvironmentTransform(floor,'floor');floor.userData.decorative=true;scene.add(floor);const wallMaterial=surfaceMaterial('architecture',visual.architecture);const backWall=new THREE.Mesh(environmentGeometry('back-wall'),wallMaterial);applyEnvironmentTransform(backWall,'back-wall');scene.add(backWall);const sideWall=new THREE.Mesh(environmentGeometry('side-wall'),wallMaterial);applyEnvironmentTransform(sideWall,'side-wall');scene.add(sideWall);const threshold=new THREE.Mesh(environmentGeometry('threshold'),surfaceMaterial('architecture',visual.threshold,{emissive:visual.thresholdEmissive,emissiveIntensity:1.2}));applyEnvironmentTransform(threshold,'threshold');scene.add(threshold);}
function addCanonicalConnections(scene:THREE.Scene,nodes:readonly THREE.Object3D[]):void{const visual=connectionVisualToken('canonical');const byId=new Map(nodes.map((node)=>[node.userData.nodeId as string,node]));const material=new THREE.LineBasicMaterial({color:visual.color,transparent:visual.transparent,opacity:visual.opacity});let connectionCount=0;for(const node of nodes){const parentId=node.userData.parentId as string|undefined;if(!parentId)continue;const parent=byId.get(parentId);if(!parent)continue;const geometry=new THREE.BufferGeometry().setFromPoints([parent.position,node.position]);const connection=new THREE.Line(geometry,material);connection.userData={parentId,childId:node.userData.nodeId,decorative:true};scene.add(connection);connectionCount+=1;}scene.userData.connectionCount=connectionCount;}
export function createThreeScene(frame:RenderFrame):ThreeSceneProjection{const visual=sceneVisualToken('dojo');const cameraToken=cameraVisualToken('standard');const scene=new THREE.Scene();const hasCanonicalRoot=frame.nodes.some((node)=>node.id==='home');scene.userData.productKind=frame.productKind;scene.userData.layoutKind=hasCanonicalRoot?'dojo-canonical-hierarchy':'fallback-grid';scene.background=new THREE.Color(visual.background);const camera=new THREE.PerspectiveCamera(cameraToken.fov,1,cameraToken.near,cameraToken.far);camera.position.set(...cameraToken.position);camera.lookAt(...cameraToken.lookAt);scene.add(new THREE.HemisphereLight(visual.hemisphereSky,visual.hemisphereGround,visual.hemisphereIntensity));addDojoArchitecture(scene);const byId=new Map(frame.nodes.map((node)=>[node.id,node]));const spatialById=new Map(frame.spatialNodes.map((node)=>[node.nodeId,node]));const manifestationById=new Map(frame.manifestationNodes.map((node)=>[node.nodeId,node]));const nodes=frame.nodes.map((node,index)=>{const isRoot=node.id==='home';const role=dojoHotspotRole(node.id);const geometryRole=isRoot?'origin':'principle';const geometry=geometryForRole(geometryRole);const geometryToken=geometryVisualToken(geometryRole);const semantic=semanticColorToken(node.id);const material=surfaceMaterial('dojo',semantic.color,{emissive:semantic.color,emissiveIntensity:isRoot?0.16:0.05});const mesh=new THREE.Mesh(geometry,material);mesh.position.copy(hasCanonicalRoot?hierarchicalPosition(node,frame.nodes,byId):gridPosition(index,frame.nodes.length));mesh.rotation.x=geometryToken.rotationX;const spatial=spatialById.get(node.id);const manifestation=manifestationById.get(node.id);mesh.userData={nodeId:node.id,label:node.label,canonicalUrl:node.canonicalUrl,parentId:node.parentId,visualRole:isRoot?'origin':role,baseZ:mesh.position.z,structure:spatial?.structure??'default',semanticRank:semantic.rank,manifestationIntensity:manifestation?.intensity??'signal'};scene.add(mesh);return mesh;});addCanonicalConnections(scene,nodes);return Object.freeze({scene,camera,nodes:Object.freeze(nodes)});}
